# ==============================================================================
# RELEASE (SELF)
# ==============================================================================
name: Release (Self)

# ==============================================================================
# TRIGGER
# ==============================================================================
on:
    push:
        branches: [ master ]

# ==============================================================================
# CONCURRENCY
# ==============================================================================
concurrency:
    group: release-${{ github.ref }}
    cancel-in-progress: false

# ==============================================================================
# PERMISSIONS
# ==============================================================================
permissions:
    contents: write
    pull-requests: write

jobs:

    # ==========================================================================
    # JOB: RELEASE
    # ==========================================================================
    release:
        uses: ./.github/workflows/release.yml
        secrets: inherit
        with:
            use-app-token: true
